### ISSUE TITLE
VPS

### ISSUE THREAD

**Issue by yuno74** [AlbertEinsteinTG/Adv-Auto-Filter-Bot#3]
can you give guide host at VPS

**Comment by AlbertEinsteinTG** [comment]
Yeh Sure Will Mention It In Readme Soon☺

**Comment by AlbertEinsteinTG** [comment]
> can you give guide host at VPS

Sorry For The Inconvenience... I Didnt Updated The ReadMe Because I'm Rewriting The Repo... So After Rewriting I Would Add Support To Switch To VPS Deploy Easily And Make A Guide To Deploy... Currently For Ppl Who Dont Know To Edit The Repo Ist Gonna Though To Deploy... So Please Wait Till My Next Update..  And Once Again Sorry For That😕
